# Generated by Django 5.1.4 on 2024-12-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='main_app.fundraiser'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
