# Generated by Django 5.1.4 on 2024-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_donation_fundraiser_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
    ]
